FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime

EXPOSE 51819
# 한글 설치
RUN apt-get update && apt-get install -y locales git
RUN localedef -f UTF-8 -i ko_KR ko_KR.UTF-8
ENV LC_ALL ko_KR.UTF-8
ENV PYTHONIOENCODING=utf-8
ENV TORCH_CUDA_ARCH_LIST=8.6

RUN mkdir /code
WORKDIR /code

# 코드 연동
COPY requirements.txt /code/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

# Set ${CONDA_ENV_NAME} to default virutal environment
 CMD  ["python", "main.py"]
