# @package _global_

defaults:
  - _self_
  - datamodule: emotion.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: bert.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: "logs/train/runs/2022-09-08_08-22-40/checkpoints/epoch_005.ckpt"

extras:
  ignore_warnings: True
