_target_: src.datamodules.CoMPM_datamodule.CoMPMDataModule

data_dir: ${paths.data_dir}MELD/multi/MELD
batch_size: 16
num_workers: 4
pin_memory: False
num_labels: 7
pretrained_model_name_or_path: ${model.net.pretrained_model_name_or_path}
max_length: 256
class_names:
  - anger
  - disgust
  - fear
  - joy
  - neutral
  - sadness
  - surprise