_target_: src.datamodules.koc_datamodule.KocDataModule

data_train: ${data_dir}/koc/train.csv
data_val: ${data_dir}/koc/val.csv
data_test: ${data_dir}/koc/test.csv
num_classes: 7
batch_size: 16
pin_memory: False
pretrained_model: ${model.pretrained_model}
max_length: 256
class_names:
  - Joy
  - Sadness
  - Surprised
  - Anger
  - Fear
  - Disgust
  - Neutrality
