_target_: src.datamodules.lm_datamodule.MaskedLMDataModule

pretrained_model_name_or_path: ${model.net.pretrained_model_name_or_path}
data_dir: ${paths.data_dir}data.csv
batch_size: 512
num_workers: 4
max_length: 512
pin_memory: False

