_target_: src.models.cos_sim_chatbot.CosSimChatbot

pretrained_model_name_or_path: jhgan/ko-sroberta-multitask

embedding_path: ${paths.data_dir}chatbot/Wellness Conversation Script Dataset/embedding.pt