_target_: src.models.bert_module.BERTLitModule

pretrained_model: klue/roberta-base
output_size: ${datamodule.num_classes}
lr: 5.0e-05
lr_scheduler: linear
optimizer: AdamW
class_names: ${datamodule.class_names}